- htdocs/downloads/index.php
- htdocs/index.php
This PR fixes an issue at https://github.com/WinMerge/winmerge/issues/515.
> Fix GitHub issue #515: Windows XP Pro SP0 vs Requirements

- htdocs/engine/page.inc
The binaries have already been uploaded to sourceforge.net.
> WinMerge version 2.16.10

- htdocs/downloads/index.php
- htdocs/engine/page.inc
The binaries have already been uploaded to sourceforge.net and github.com
ARM64 support has been added to this release.
> WinMerge version 2.16.12

- htdocs/engine/page.inc
The binaries have already been uploaded to sourceforge.net and github.com
This version mainly includes plugin enhancements.
> WinMerge version 2.16.14

- htdocs/engine/page.inc
The binaries have already been uploaded to sourceforge.net and github.com
> WinMerge version 2.16.16

- htdocs/engine/page.inc
I tried to upload to sourceforge.net, but I gave up uploading to sourceforge.net because the Android device for 2FA broke down and the recovery code I saved did not work.
> WinMerge version 2.16.18

- po/pt_PT.po
> Update portuguese translation

- po/co.po
Hello,
This is an update of **Corsican** (co) localization for version 2.16.20.
Best regards,
Patriccollu.
> Update Corsican translation for 2.16.20

- htdocs/.htaccess
- htdocs/engine/page.inc
> WinMerge 2.16.22

- htdocs/.htaccess
- htdocs/engine/page.inc
This release adds an experimental feature to highlight text differences in web pages.
> WinMerge 2.16.24

- htdocs/.htaccess
- htdocs/engine/page.inc
> WinMerge 2.16.26

- htdocs/engine/page.inc
This PR fixes an incorrect SHA256 value reported in issue #51.
> Fix issue #51: 2.16.28 Full-Src - Wrong SHA256

- htdocs/.htaccess
- htdocs/engine/page.inc
> WinMerge 2.16.30

- htdocs/.htaccess
- htdocs/engine/page.inc
> WinMerge 2.16.32

- htdocs/.htaccess
- htdocs/engine/page.inc
Binaries have already been uploaded to both sourceforge.net and github.com.
> WinMerge 2.16.38

- htdocs/.htaccess
- htdocs/engine/page.inc
Binaries have already been uploaded to both sourceforge.net and github.com.
> WinMerge 2.16.40

- po/zh_CN.po
Here comes the simplified Chinese translation of the WinMerge website.
> add simplified Chinese translation

- po/co.po
Hello,
This is an update of **Corsican** (co) localization for version 2.16.44.
Best regards,
Patriccollu.
> Update Corsican translation for website 2.16.44

- po/co.po
Hello,
This is an update of **Corsican** (co) localization for version 2.16.46.
Best regards,
Patriccollu.
> Update Corsican translation for 2.16.46

- po/tr.po
Website Turkish translation update
> Website Turkish translation update

- po/ta.po
> தமிழ் (Tamil) Translation Added

- po/ta.po
Small correction in Tamil language file in the downloads page
> Tamil minor fix
